### ISSUE TITLE
.unique call that doesn't do anything

### ISSUE THREAD

**Issue by AlexDaniel** [hythm7/Grid#4]
See this code:
https://github.com/hythm7/Grid/blob/1ac012aa3a162e6635d79528647d2bcdaa6038ee/lib/Grid.pm#L399

In this case, elements in `@index` will not be unique, because essentially it parses as  `(@index .= sort).unique;`

Instead you should use `@index .= sort .= unique;`.

https://github.com/rakudo/rakudo/issues/3621
https://github.com/Raku/doc/issues/3333

**Comment by hythm7** [comment]
Thanks @AlexDaniel
